### ISSUE TITLE
[BUG] cacache ignores npm cache config

### ISSUE THREAD

**Issue by Mitsunee** [npm/cacache#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my npmrc file contains

```
prefix=${XDG_DATA_HOME}/node
cache=${XDG_CACHE_HOME}/npm
init-module=${XDG_CONFIG_HOME}/npm/config/npm-init.js
```

cacache ignores this frequently causing a `~/.npm` directory to reappear.

### Expected Behavior

cacache should always use the configured path (which in this case is `~/.cache/npm/`) when used through npm. 

### Steps To Reproduce

1. Edit npmrc as shown above
2. perform operation that uses caching (presumably a global package install? That and `npm publish` are all I used npm for)
3. the `~/.npm` directory reappears with the new cache.

### Environment

- npm: npm@8.15.0
- Node: v16.16.0
- OS: Fedora 36
- platform: x86_64

**Comment by Mange** [comment]
I would even vote for just having it behave like a proper library in the first place and just use the cache dir as intended. It's really strange seeing a "modern" app writing stuff in the user's home directory like that. It's a bit like if it put a directory on the desktop of a macOS or Windows machine.

Is there a reason for not following conventions here? Compatibility with older Node libraries?

**Comment by wraithgar** [comment]
cacache does not have a default cache location. If one is not provided it errors.  This looks to be either a bug or a side effect of something else npm is doing (it writes many things to that folder).
