### ISSUE TITLE
[ISSUE] Explain to me why this is a stupid use of cacache (storing simple key/value pairs with a simplified cacache interface)

### ISSUE THREAD

**Issue by advename** [npm/cacache#120]
I've been looking for solid, stable and well maintained Node.js file caching libraries. (Un)Fortunately, cacache was the only one that I could find.

Now, having general experience with remote caching, looking first time at cacache documentation was overwhelming. Tarball why? Integrity what? ...

After experimenting a bit around, I believe I figured out the basics and wrote a simplified API around it.

```js
// cache.js
import path from "path";
import cacache from "cacache";

const cachePath = path.join(__dirname, ".cache");

/**
 * Simplified Cache API written on top of cacache
 * This interface makes using cacache bit more straightforward without
 * deeper understanding of caching itself.
 * @see https://github.com/npm/cacache
 */

/**
 * Set or override key/value in the cache
 */
const put = async (key, value) => {
    const writeAction = await cacache.put(
        cachePath,
        key,
        JSON.stringify(value)
    );

    return writeAction;
};

/**
 * Retrieve a value from the cache.
 */
const get = async (key) => {
    const readAction = await cacache.get(cachePath, key);
    /**
     * Returned "data" key contains data as a Buffer object
     * Convert Buffer binary contents to string
     * @see https://nodejs.org/en/knowledge/advanced/buffers/how-to-use-buffers/#reading-from-buffers
     */
    const dataJSON = readAction.data.toString();
    const data = JSON.parse(dataJSON);
    return data;
};

const remove = async (key) => {
    const removeAction = await cacache.rm.entry(cachePath, key, {
        removeFully: true,
    });
    return removeAction;
};

/**
 * Clears the entire cache
 */
const destroy = async () => {
    const destroyAction = await cacache.rm.all(cachePath);
    return destroyAction;
};

export const cache = {
    put,
    get,
    remove,
    destroy,
};
```

Before putting this in a production environment, convince me why the above simplified interface is a bad idea for storing key/value pairs, where values may be string, numbers or objects with 500 properties?

**Comment by horak** [comment]
I have no familiarity with cacache, but am equally overwhelmed and looking for an interface exactly as you describe. Do you use this in production for your own needs?

Would you be interested in also making / including an equally concise & simple cacache initialization? I'm imagining something like:

```js
var cache = cacache({
    location: 'some/folder/or/file',
    name: 'footheflowerhorn',
    duration: 1000 * 3600 * 24
    persist: true
});
```

**Comment by advename** [comment]
What would be the usage of persist? Cacache is a file based storage?

**Comment by wraithgar** [comment]
This module is pretty customized for the needs of the npm cli.  It should work just fine for a generic key/value cache even if it is a bit overweight for that.

**Comment by advename** [comment]
@wraithgar thanks for the feedback.

My question was, however, regarding the implementation that I've created. I'm too much of a novice to know or see if I missed something important out.
