### ISSUE TITLE
[BUG] @npmcli/move-file is dilicated

### ISSUE THREAD

**Issue by Harryk13** [npm/cacache#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### Expected Behavior

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### Steps To Reproduce

1. In this environment...
nodeJS 18.16.0
2. With this config...
3. Run '...'
npm i cacache
4. See error...
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### Environment

- npm: 9.5.1
- Node: 18.16.0
- OS: Windows 11, Ubuntu 20 & 22
- platform:

**Comment by wraithgar** [comment]
`node-gyp` is a semver major behind on `make-fetch-happen` which is being worked out in that repo already.
