### ISSUE TITLE
[FEATURE] Add CLI support to list & remove the cache content

### ISSUE THREAD

**Issue by ilg-ul** [npm/cacache#26]
# What / Why

I am using pacote to download and cache, in addition to reasonably sized source libraries, large binaries (like toolchain distributions, hundreds of MB) and I would appreciate a CLI solution to enumerate the content of the cache, such that later to be able to selectively remove some cached files. For now the only method I found was to completely remove the cache, which is far from optimal.

Thank you,

Liviu

**Comment by wraithgar** [comment]
We're not planning on adding cli support to cacache specifically.  Most of our libs that don't already have a cli are also likely not getting one.  If we do add them they'll be in a separate package (since cli breaking changes happen at a different cadence than module ones)
