### ISSUE TITLE
upgrade tar to 6.2.1

### ISSUE THREAD

**Issue by mvanzoest** [npm/cacache#263]
tar < 6.2.1 has been flagged by GitHub with a moderate security vulnerability, and it is recommended to upgrade to >= 6.2.1

See [Denial of service while parsing a tar file due to lack of folders count validation](https://github.com/advisories/GHSA-f5x3-32g6-xq36)

**Comment by wraithgar** [comment]
This is a module, not an end product.  The tar entry in package.json is `"tar": "^6.1.11"` which allows consumers to update themselves.  There is no functional difference between them updating their subdependency and this module publishing a new version.  The end user has to update either way.

Historically we don't cut a version for something like this.  Semver is doing it job.
