### ISSUE TITLE
_cacache installs in root

### ISSUE THREAD

**Issue by oy1958** [npm/cacache#29]
### _cacache installs in root folder of project

when i install react via npm there is a -cacache-folder in root,
under that there is also a _lock folder.

this  didn't happen before
that gives hard times for git, 5000 files waiting 
node-modules folder has already a _cacache

**Comment by isaacs** [comment]
Can you please share the command you ran that caused this to happen?  Thanks.

**Comment by oy1958** [comment]
> Can you please share the command you ran that caused this to happen? Thanks.

when installing dependencies npm recreated -cacache and locks folders in root of my project
and git saw 5000 files newly created.
i reinstalled node and npm,  that solved the issue
i don't know what the cause had been.

**Comment by isaacs** [comment]
Ok.  I'm going make peace with this unsolved mystery, then :)
