### ISSUE TITLE
[QUESTION] tell if item exists

### ISSUE THREAD

**Issue by alex-jitbit** [npm/cacache#35]
Can't find an easy way to tell if object by key exists without actually getting it

**Comment by samblackmore** [comment]
Is this what you want? [`cacache.get.info(cache, key)`](https://github.com/npm/cacache#--cacachegetinfocache-key---promise)
> Looks up key in the cache index, returning information about the entry if one exists.

**Comment by wraithgar** [comment]
@samblackmore is correct that's the best method to use if you don't need the data.
