### ISSUE TITLE
[SECURITY] v10.x.x security vulnerability introduced through mkdirp/minimist.

### ISSUE THREAD

**Issue by YellowPanda11** [npm/cacache#36]
mkdirp should be on 0.5.3 at least to bring in the patched minimist version.

ref: https://snyk.io/test/npm/mkdirp/0.5.0
ref: https://github.com/isaacs/node-mkdirp/releases/tag/v0.5.3

**Comment by rharriso** [comment]
Is it necessary to continue to use `mkdirp`? Recursive directory creation is available in node v10.12. Thats the oldest active LTS.

**Comment by isaacs** [comment]
If you just update, you'll get mkdirp 0.5.5, which doesn't have the problem.  Latest versions of cacache use mkdirp 1.x, which doesn't use minimist at all.

**Comment by isaacs** [comment]
@rharriso Yes, because cacache v10 supports node back to v6, and cacache 15 supports node 10.0 and up.
